@Gerenciador_de_Tarefas_HostAddress = http://localhost:5034

GET {{Gerenciador_de_Tarefas_HostAddress}}/user/
Accept: application/json




###
POST {{Gerenciador_de_Tarefas_HostAddress}}/user/register
Content-Type: : application/json

{
    
   "email": "user@example.com",
  "userName": "string",
  "password": "string",
  "passwordConfirmation": "string"

}
###



POST {{Gerenciador_de_Tarefas_HostAddress}}/user/login HTTP/1.1
content-Type:  application/json
Accept: aplication/json

{
  "userName": "daniel",
  "password": "02362228Im*"
}


###

GET {{Gerenciador_de_Tarefas_HostAddress}}/dados/daniel
Accept: application/json
Authorization: Bearer
###